# Generated by Django 3.1.4 on 2020-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('catogary', models.CharField(choices=[('NUM1', 'Conditioner'), ('NUM2', 'Non-Conditioner'), ('NUM3', 'Deluxe'), ('Man', 'Men'), ('Woman', 'Women')], max_length=15)),
                ('Beds', models.IntegerField()),
                ('Capacity', models.IntegerField()),
            ],
        ),
    ]
