# Generated by Django 3.1.4 on 2020-12-31 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='catogary',
            field=models.CharField(choices=[('Conditioner', 'Conditioner'), ('Non-Conditioner', 'Non-Conditioner'), ('Deluxe', 'Deluxe'), ('Single', 'Single Room'), ('Double', 'Double Room ')], max_length=15),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chek_in', models.DateField()),
                ('chek_out', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
