# Generated by Django 3.1.4 on 2020-12-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201231_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='chek_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='chek_out',
            field=models.DateTimeField(),
        ),
    ]
