# Generated by Django 3.1.4 on 2020-12-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201231_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='chek_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='chek_out',
            new_name='check_out',
        ),
    ]
