# Generated by Django 3.1.4 on 2021-01-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201231_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='catogary',
            new_name='category',
        ),
    ]
