# Generated by Django 3.1.4 on 2021-01-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_room_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
