# Generated by Django 3.1.4 on 2021-01-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_number',
        ),
    ]
