# Generated by Django 3.1.4 on 2021-01-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_booking_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Triple', 'Triple'), ('Non-Conditioner', 'Non-Conditioner'), ('Deluxe', 'Deluxe Rooom'), ('Single', 'Single Room'), ('Double', 'Double Room ')], max_length=15),
        ),
    ]
