# Generated by Django 3.1.4 on 2021-01-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20210128_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('Triple', 'Triple Room'), ('Non-Conditioned 2', 'Non-Conditioned'), ('Non-Conditioned 3', 'Non-Conditioned'), ('Deluxe', 'Deluxe Rooom'), ('Single', 'Single Room'), ('Double', 'Double Room ')], max_length=20),
        ),
    ]
