# Generated by Django 3.1.4 on 2021-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20210227_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='Capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(blank=True, choices=[('Triple', 'Triple Room'), ('Non-Conditioned 2', 'Non-Conditioned'), ('Non-Conditioned 3', 'Non-Conditioned '), ('Deluxe', 'Deluxe Rooom'), ('Single', 'Single Room'), ('Double', 'Double Room ')], max_length=20, null=True),
        ),
    ]
