# Generated by Django 3.1.4 on 2021-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_auto_20210227_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
