# Generated by Django 3.1.4 on 2021-02-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
